# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [2]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [3]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)

['hello']


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [6]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [4]:
import numpy as np
array=np.arange(20,36)
print("Array of the integers from 20 to 35 ")
print(array)

Array of the integers from 20 to 35 
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
import numpy as np
np.arange(0,9).reshape((3,3))
([[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]])

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [10]:
import numpy as np 
a = np.array([[1,2,3]]) 

print ('First array:')
print (a) 
print ('\n')  
b = np.array([[4,5,6]]) 

print ('Second array:')
print (b) 
print ('\n')  
# both the arrays are of same dimensions 

print ('Joining the two arrays along axis 0:')
print(np.concatenate((a,b)))
print ('\n')  

print ('Joining the two arrays along axis 1:') 
print (np.concatenate((a,b),axis = 1))

First array:
[[1 2 3]]


Second array:
[[4 5 6]]


Joining the two arrays along axis 0:
[[1 2 3]
 [4 5 6]]


Joining the two arrays along axis 1:
[[1 2 3 4 5 6]]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [9]:
import pandas as pd


data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)


   calories  duration
0       420        50
1       380        40
2       390        45


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [8]:
import pandas as pd
d = pd.date_range(start='1/1/2023',end='10/2/2023')
print(d)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [7]:
import pandas as pd
a=[[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
print(type(a))

for b in a:
    for j in b:
        print(j)

dt=zip(a)
df=pd.DataFrame(dt,columns=["d"])
print(type(df))
print(df)

<class 'list'>
1
aaa
22
2
bbb
25
3
ccc
24
<class 'pandas.core.frame.DataFrame'>
              d
0  [1, aaa, 22]
1  [2, bbb, 25]
2  [3, ccc, 24]
